<?php   use Application\Configuration;
$configuration = new Configuration();
?>
<div id="login-overlay" class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Login to the system</h4>
        </div>
        <div class="modal-body">
            <div class="row">
                <div class="col col-xs-12">
                    <div class="well">
                        <form id="loginForm" method="POST" action="/login/" novalidate="novalidate">
                            <div class="form-group">
                                <div class="input-group margin-bottom-sm">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa-solid fa-fw fa-envelope"></i></span></div>
                                    <input type="text" class="form-control" id="Email" name="Email" value="" required="" title="Please enter you username" placeholder="example@gmail.com">
                                </div>


                                <span class="help-block"></span>
                            </div>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa-solid fa-fw fa-key"></i></span></div>
                                    <input type="password" class="form-control" id="Password" name="Password" value="" required="" title="Please enter your password">
                                </div>
                                <span class="help-block"></span>
                            </div>
                            <div id="loginErrorMsg" style='display:none;' class="alert alert-danger" role="alert">Wrong username or password</div>
                            <button type="submit" class="btn btn-success btn-block">Login</button>
<!--                            <a href="/forgotpassword" class="btn btn-default btn-block">Help to login</a>-->
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>