<form id="loginForm" method="POST" action="/login/" novalidate="novalidate">
<div class="d-flex justify-content-center align-items-center" style="height: 100vh;">
    <div class="card">
        <div class="card-body">
            <div class="row text-center mt-3 mb-5">
                <div class="logo-circle col-3 d-grid mx-auto">
                    <i class="bi bi-bookmarks-fill logo"></i>
                </div>
            </div>
            <div class="row text-center mb-4">
                <h3>LOG IN</h3>
            </div>
            <div class="row mb-3">
                <div class="input-group">
                    <input type="email" class="form-control" id="Email" name="Email" value="" required placeholder="EMAIL">
                </div>
            </div>
            <div class="row mt-2 mb-5">
                <div class="input-group">
                    <input type="password" class="form-control" id="Password" name="Password" value="" required placeholder="PASSWORD">
                </div>
            </div>
            <div class="row mb-3">
                <div class="d-grid gap-2 col-4 mx-auto">
                    <button type="submit" class="btn login-btn"><i class="bi bi-caret-right-fill"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
</form>