<?php $coursedetails = $this->coursedetails[0]; ?>

<div class="row course_details_header mb-3" style="background-color: #<?=$coursedetails['CardColor']?>;">
    <div class="col-auto ms-auto px-4 py-3">
        <a class="clickable" onclick="editCourse(<?= $coursedetails['CourseID'] ?>)" style="font-size: 2rem;"><i class="bi bi-pencil-square"></i></a>
    </div>
</div>

<div class="row mb-3">
    <div class="col-auto me-auto">
        <h1><?=$coursedetails['CourseName']?></h1>
        <br>
        <h3><?= ($coursedetails['CourseNumber'] ?? '') ?></h3>
    </div>
    <div class="col-auto ms-auto">
        <a class="btn btn-primary" onclick="addNewAssignment(<?= $coursedetails['CourseID'] ?>)"><i class="bi bi-plus"></i> New Assignment</a>
    </div>
</div>

<?php include_once $_SERVER['DOCUMENT_ROOT'].'/module/Assignments/view/assignments/assignments/ajax/course.assignments.list.php'; ?>