<?php
use Courses\Semesters;

$semesters = new Semesters();
$allsemesters = $semesters->getAll();
$currentsemester = $semesters->getCurrentSemester();
?>

<div class="row">
    <div class="col-auto me-auto">
        <select id="semesterSelect">
            <?php foreach ($allsemesters as $semester) { ?>
                <option value="<?= $semester['SemesterID']; ?>" <?= $semester['SemesterID'] == $currentsemester ? 'selected' : '' ?>><?= $semester['SemesterName']; ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="col-auto ms-auto">
        <a class="btn btn-primary" onclick="addNewCourse()"><i class="bi bi-plus"></i> New Course</a>
    </div>
</div>
<div id="courseList" class="row mb-3"></div>

<script>
    $(document).ready(function() {
        let initialSemester = $('#semesterSelect').val();
        loadCourses(initialSemester);
        $('#semesterSelect').change(function() {
            let selectedSemester = $(this).val();
            loadCourses(selectedSemester);
        });
    });
</script>