<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Assignments\Module'                        => __DIR__ . '/Module.php',
    'Assignments\Controller\AssignmentsController' => __DIR__ . '/src/Assignments/Controller/AssignmentsController.php',
    'Assignments\Framework\TestCase'        => __DIR__ . '/tests/Assignments/Framework/TestCase.php',
    'Assignments\SampleTest'                => __DIR__ . '/tests/Assignments/SampleTest.php',
);
