<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Courses\Module'                        => __DIR__ . '/Module.php',
    'Courses\Controller\CoursesController' => __DIR__ . '/src/Courses/Controller/CoursesController.php',
    'CoursesTest\Framework\TestCase'        => __DIR__ . '/tests/Courses/Framework/TestCase.php',
    'CoursesTest\SampleTest'                => __DIR__ . '/tests/Courses/SampleTest.php',
);
