<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tasks\Module'                        => __DIR__ . '/Module.php',
    'Tasks\Controller\TasksController' => __DIR__ . '/src/Tasks/Controller/TasksController.php',
    'TasksTest\Framework\TestCase'        => __DIR__ . '/tests/Tasks/Framework/TestCase.php',
    'TasksTest\SampleTest'                => __DIR__ . '/tests/Tasks/SampleTest.php',
);
