<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Controller\ApplicationController' => __DIR__ . '/src/Application/Controller/ApplicationController.php'
);
