<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Announcements\Module'                        => __DIR__ . '/Module.php',
    'Announcements\Controller\AnnouncementsController' => __DIR__ . '/src/Announcements/Controller/AnnouncementsController.php',
    'AnnouncementsTest\Framework\TestCase'        => __DIR__ . '/tests/Announcements/Framework/TestCase.php',
    'AnnouncementsTest\SampleTest'                => __DIR__ . '/tests/Announcements/SampleTest.php',
);
