<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Connections\Module'                        => __DIR__ . '/Module.php',
    'Connections\Controller\ConnectionsController' => __DIR__ . '/src/Connections/Controller/ConnectionsController.php',
    'ConnectionsTest\Framework\TestCase'        => __DIR__ . '/tests/Connections/Framework/TestCase.php',
    'ConnectionsTest\SampleTest'                => __DIR__ . '/tests/Connections/SampleTest.php',
);
