<?= $this->doctype() ?>

<html lang="en">
    <head>
        <title>Assignment Tracker</title>
        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php include_once 'inc/css.php'; ?>
        <?php include_once 'inc/js.php'; ?>
    </head>

    <body>
        <nav class="navbar" role="navigation" style="height: 5rem"><div class="container"><?php include_once 'inc/navbar.php';?></div></nav>
        <div class="container">
            <?= $this->content ?>

            <footer class="fixed-bottom">Ooga Booga</footer>
        </div>
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js')) ?>
    </body>
</html>
