<?= $this->doctype() ?>

<html lang="en">
    <head>
        <title>Assignment Tracker</title>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

//        echo '<pre>'; die(print_r($_SESSION));

        $userdetails = (new \Account\Users)->Details($_SESSION['AssignmentSession']['User'][0]['UserID'])[0];
        $themedetails = (new \Account\Themes)->Details($userdetails['ThemeID'])[0];

        include_once 'inc/assets.php';?>
        <link rel="stylesheet" href="/css/themes/<?= $themedetails['ThemeSheet'] ?>.css"/>
        <link rel="stylesheet" href="/css/main.css"/>
    </head>
    <body>
        <header>
            <nav class="navbar" role="navigation">
                <div class="container">
                    <?php include_once 'inc/navbar.php';?>
                </div>
            </nav>
        </header>

        <div class="container-fluid mb-auto">
            <?= $this->content ?>
        </div>

        <footer class="mt-3">Ooga Booga</footer>

        <?php include_once 'inc/modal.php';
        include_once 'inc/spinner.php';
        echo $this->inlineScript(); ?>
    </body>
</html>
