<?= $this->doctype() ?>

<html lang="en">
    <head>
        <title>Assignment Tracker</title>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        Use Settings\Themes;
        Use Application\Users;

        $userdetails = (new Users)->getDetails($_SESSION['AssignmentSession']['User'][0]['UserID'])[0];
        $themedetails = (new Themes())->getDetails($userdetails['ThemeID'])[0];

        include_once 'inc/assets.php';?>
        <link rel="stylesheet" href="/css/themes/<?= $themedetails['ThemeSheet'] ?>.css"/>
        <link rel="stylesheet" href="/css/main.css"/>
    </head>
    <body>
        <header>
            <nav class="navbar" role="navigation" style="min-height: 10vh">
                <div class="container">
                    <?php include_once 'inc/navbar.php';?>
                </div>
            </nav>
        </header>

        <div class="container" style="min-height: 85vh">
            <?= $this->content ?>
        </div>

        <footer style="min-height: 5vh">Ooga Booga</footer>

        <?php include_once 'inc/modal.php';
        echo $this->inlineScript(); ?>
    </body>
</html>
