<?= $this->doctype() ?>

<html lang="en">
<head>

    <title>Assignment Software Login</title>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    include_once 'inc/assets.php';?>
    <link rel="stylesheet" href="/css/login.css"/>

</head>
<body>

    <?php echo $this->content;
    echo $this->inlineScript(); ?>

</body>
</html>
