<?php use \Tasks\Tasks;
$unlistedtasklist = (new Tasks)->getUnlistedByUserID($_SESSION['AssignmentSession']['User'][0]['UserID']);

$tasklistslist = (new \Tasks\TaskLists)->getAllByUserID($_SESSION['AssignmentSession']['User'][0]['UserID']);

//print_r($unlistedtasklist);
print_r($tasklistslist);
?>


<div class="row row-cols-<?= count($tasklistslist) >= 3 ? '3' : (count($tasklistslist) + 1) ?>">
    <div class="col">
        <div class="card">
            <div class="card-header">
                <h5>General</h5>
            </div>
            <div class="card-body">
                <ul class="m-0" id="tasksGeneral" style="min-height: 50px;">
                    <?php if (!empty($unlistedtasklist)) {
                        foreach ($unlistedtasklist as $unlistedtask) { ?>
                            <li class="row m-0 p-0 draggable-task-item">
                                <div class="col-auto p-0 align-content-center draggable-handle">
                                    <i class="bi bi-grip-vertical"></i>
                                </div>
                                <div class="col ps-3 align-content-center draggable-content">
                                    <input class="custom-checkbox" type="checkbox" <?= $unlistedtask['Complete'] == 1 ? 'checked' : '' ?>>
                                    <h4 class=" ps-3 d-inline"><?= $unlistedtask['TaskTitle'] ?></h4>
                                </div>
                            </li>
                        <?php }
                    } ?>
                </ul>
            </div>
        </div>
    </div>

    <?php if (!empty($tasklistslist)) {
        foreach ($tasklistslist as $tasklist) { ?>
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5><?= $tasklist['TaskListTitle'] ?></h5>
                    </div>
                    <div class="card-body">
                        <ul class="m-0" id="tasksList<?= $tasklist['TaskListID'] ?>" style="min-height: 50px;">
                            <?php $taskslist = (new Tasks)->getAllByTaskListID($tasklist['TaskListID']);
                            if (!empty($taskslist)) {
                                foreach ($taskslist as $task) { ?>
                                    <li class="row m-0 p-0 draggable-task-item">
                                        <div class="col-auto p-0 align-content-center draggable-handle">
                                            <i class="bi bi-grip-vertical"></i>
                                        </div>
                                        <div class="col ps-3 align-content-center draggable-content">
                                            <input class="custom-checkbox" type="checkbox">
                                            <h4 class=" ps-3 d-inline"><?= $task['TaskTitle'] ?></h4>
                                        </div>
                                    </li>
                                <?php }
                            } ?>
                        </ul>
                    </div>
                </div>
            </div>
        <?php }
    } ?>
</div>


<script>
    // $('#tasksSortable').sortable({
    //     animation: 150,
    //     handle: ".draggable-handle",
    //     ghostClass: "draggable-ghost",
    //     group: "group",
    //     swapThreshold: 0.75,
    // })
    // $('#tasksSortable2').sortable({
    //     animation: 150,
    //     handle: ".draggable-handle",
    //     ghostClass: "draggable-ghost",
    //     group: "group",
    //     swapThreshold: 0.75,
    // })

    $('.draggable-task-item').on("dragstart", function (ev) {
        const dragimage = new Image();
        dragimage.src = "";
        ev.originalEvent.dataTransfer.setDragImage(dragimage, 0, 0);
    })
</script>