<?php //if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
//$ip = $_SERVER['HTTP_CLIENT_IP'];
//} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
//$ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
//} else {
//$ip = $_SERVER['REMOTE_ADDR'];
//}
//$data['IPAddress'] = $ip;

//Use Application\Logs;
//
//$tablename = 'users';
//$additemid = '3';
//$newitem = array("FirstName" => "Log", "Test" => "Mustang", "Email" => "logtest@assignment.com");
//
//(new Logs)->logAddItem($tablename, $additemid, $newitem);

//echo "<pre>"; print_r($_SERVER);
//echo "<pre>"; print_r($ip);?>


<div class="mb-4 card rounded-3">
    <div class="card-header">This is a placeholder</div>
    <div class="card-body">Seriously, there's nothing here yet</div>
</div>